// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SbnApplicationUTS2.Data;

#nullable disable

namespace SbnApplicationUTS2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251103142701_UpdateBuyerTable")]
    partial class UpdateBuyerTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SbnApplicationUTS2.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Jumlah")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SBNId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TanggalTransaksi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalHarga")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("SBNId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("SbnApplicationUTS2.Models.Buyer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("SbnApplicationUTS2.Models.SBN", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Harga")
                        .HasColumnType("integer");

                    b.Property<string>("Jenis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kode_Sbn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nama_SBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SBNs");
                });

            modelBuilder.Entity("SbnApplicationUTS2.Models.Asset", b =>
                {
                    b.HasOne("SbnApplicationUTS2.Models.Buyer", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SbnApplicationUTS2.Models.SBN", "SBN")
                        .WithMany()
                        .HasForeignKey("SBNId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("SBN");
                });
#pragma warning restore 612, 618
        }
    }
}
